azs:
- name: z1
- name: z2
- name: z3

vm_types:
- name: minimal
  cloud_properties:
    instance_type: Standard_A1_v2
    availability_set: common
    root_disk:
      size: 20480
- name: master
  cloud_properties:
    instance_type: Standard_A1_v2
    availability_set: master
    root_disk:
      size: 20480
- name: worker
  cloud_properties:
    instance_type: Standard_D3_v2
    availability_set: worker
    root_disk:
      size: 102400

networks:
- name: default
  type: manual
  subnets:
  - range: ((internal_cidr))
    gateway: ((internal_gw))
    azs: [z1, z2, z3]
    dns: [((dns_recursor_ip))]
    reserved: [((internal_gw))/30]
    cloud_properties:
      virtual_network_name: ((vnet_name))
      subnet_name: ((subnet_name))
      security_group: ((default_security_group))
- name: vip
  type: vip

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: worker
  network: default
